import { Product, CustomerReview } from '@/types/types'

export const products: Product[] = [
    // {
    //     id: '1',
    //     name: 'SDD Burgundy',
    //     description: '20inch paired with 5by5 closure',
    //     price: 498000,
    //     status: 'available',
    //     images: ['/images/hair-1.jpg'],
    //     color: 'Burgundy',
    //     length: '20inch',
    //     closure: '5by5',
    //     category: 'Closure Set',
    //     featured: true,
    // },
    {
        id: '1',
        name: 'Pixie Curls',
        description: '300g, 22inch paired with 5by5 closure',
        price: 590000,
        status: 'available',
        images: ['/images/short-pixie.png'],
        color: 'Burgundy',
        length: '22 inch',
        closure: '5by5',
        category: 'Closure Set',
        featured: true,
    },
    {
        id: '2',
        name: 'Deep Wave Frontal Set',
        description: '24inch with 13by4 lace frontal',
        price: 620000,
        status: 'sold_out',
        images: ['/images/short-brown-bone-straight.png'],
        color: 'Natural Black',
        length: '24inch',
        closure: '13by4',
        category: 'Frontal Set',
    },
    {
        id: '3',
        name: 'Kinky Straight Bundle',
        description: '18inch raw kinky straight, 3 bundles',
        price: 380000,
        status: 'available',
        images: ['/images/long-pixie-curls.png'],
        color: 'Natural Black',
        length: '18inch',
        category: 'Bundles',
    },
    {
        id: '4',
        name: 'Body Wave Luxury',
        description: '22inch body wave with 5by5 HD closure',
        price: 545000,
        status: 'available',
        images: ['/images/shoulder-bone-straight.png'],
        color: 'Natural Black',
        length: '22inch',
        closure: '5by5 HD',
        category: 'Closure Set',
    },
    {
        id: '5',
        name: 'Loose Deep Wave',
        description: '26inch loose deep wave frontal set',
        price: 710000,
        status: 'available',
        images: ['/images/long-brown-bone-straight.png'],
        color: 'Natural Black',
        length: '26inch',
        closure: '13by6',
        category: 'Frontal Set',
    },
    {
        id: '6',
        name: 'Silky Straight Blonde',
        description: '20inch silky straight, #613 blonde',
        price: 590000,
        status: 'sold_out',
        images: ['/images/waves.png'],
        color: 'Blonde',
        length: '20inch',
        category: 'Bundles',
    },
]

export const reviews: CustomerReview[] = [
    { id: '1', name: 'Adaeze Okafor', handle: '@adaeze_luxury', image: '/images/customer-1.jpg', quote: 'This hair is everythinggg, so soft!', rating: 5, product: 'SDD Burgundy' },
    { id: '2', name: 'Bimpe Adeyemi', handle: '@bimpe.hair', image: '/images/customer-2.png', quote: 'Quality is unmatched, will always come back!', rating: 5, product: 'Deep Wave Frontal' },
    { id: '3', name: 'Kemi Okonkwo', handle: '@kemi_glam', image: '/images/customer-1.jpg', quote: 'Didifairy never disappoints. Period.', rating: 5, product: 'Body Wave Luxury' },
    { id: '4', name: 'Titi Fashola', handle: '@titi.luxe', image: '/images/customer-1.jpg', quote: 'Got so many compliments, thank you!', rating: 5, product: 'Kinky Straight' },
    { id: '5', name: 'Sola Abiodun', handle: '@sola_vibes', image: '/images/customer-1.jpg', quote: 'Fast delivery, premium packaging!', rating: 5, product: 'SDD Burgundy' },
    { id: '6', name: 'Precious Eze', handle: '@precious_hair', image: '/images/customer-1.jpg', quote: 'Better than the pictures!', rating: 5, product: 'Loose Deep Wave' },
]